function [C_fft_interp, x_fft, C_fft] = executeFFTMethod(x_grid, F0, DF, p_plus, p_minus, mu, M, dz)
    % EXECUTEFFTMETHOD Computes Call prices over a global grid using FFT and 
    % interpolates the results to match specific requested moneyness points.
    %
    % Inputs:
    %   x_grid  - Array of requested log-moneyness values (x = ln(F0/K))
    %   F0      - Forward price
    %   DF      - Discount Factor
    %   p_plus  - Positive jump parameter for the characteristic function
    %   p_minus - Negative jump parameter for the characteristic function
    %   mu      - Martingale drift
    %   M       - Grid size parameter (N = 2^M)
    %   dz      - Integration step size for the FFT
    %
    % Outputs:
    %   C_fft_interp - Array of interpolated Call prices exactly at x_grid
    %   x_fft        - Full log-moneyness grid generated by the FFT
    %   C_fft        - Full array of Call prices generated by the FFT

    fprintf('--- Method d: Fast Fourier Transform (FFT) ---\n');
    
    % Call the base FFT pricing function
    [x_fft, C_fft] = computeI_FFT(F0, DF, p_plus, p_minus, mu, M, dz);
    
    % Interpolate FFT results to match our specific requested moneyness points
    % We use spline interpolation for smooth approximation between grid points
    C_fft_interp = interp1(x_fft, C_fft, x_grid, 'spline');
    
    % Print the results nicely to the console
    for i = 1:length(x_grid)
        fprintf('FFT Price at x = %7.2f%%: %8.4f\n', x_grid(i)*100, C_fft_interp(i));
    end
end