function Implied_Vol_Comparison(K_vec, sigma_vec, model_implied_vol)
% Implied_Vol_Comparison plots the market implied volatility 
% against the model implied volatility.
%
% Inputs:
%   K_vec             : Array of strikes (or moneyness) used in the dataset
%   sigma_vec         : Array of market implied volatilities
%   model_implied_vol : Array of implied volatilities generated by the calibrated model

% Create a new figure
figure('Name', 'Implied Volatility Comparison', 'Color', 'w');

% Plot Market Implied Volatility (using markers to show exact data points)
plot(K_vec, sigma_vec, 'bo-', 'LineWidth', 1.5, 'MarkerFaceColor', 'b', 'MarkerSize', 6);
hold on;

% Plot Model Implied Volatility
plot(K_vec, model_implied_vol, 'r*-', 'LineWidth', 1.5, 'MarkerSize', 6);
hold off;

% Formatting the plot for clarity
grid on;
xlabel('Strike (K) / Moneyness', 'FontWeight', 'bold');
ylabel('Implied Volatility (\sigma)', 'FontWeight', 'bold');
title('Volatility Surface Calibration: Market vs. Normal Mean-Variance Mixture (\alpha=2/3)', 'FontSize', 12);

% Add a legend to distinguish the curves
legend('Market Implied Volatility', 'Model Implied Volatility', 'Location', 'best');

end